/* eslint no-magic-numbers: off, quote-props: off  */
module.exports = {
    root: true,

    parserOptions: {
        sourceType: "module",
        ecmaVersion: 8,
        ecmaFeatures: {}
    },

    env: {
        browser: true,
        node: true,
        es6: true,
    },

    // http://eslint.org/docs/rules/
    rules: {

        // possible errors:
        "no-await-in-loop": "warn",
        "no-compare-neg-zero": "error",
        "no-cond-assign": ["error", "except-parens"],
        "no-console": "off",
        "no-constant-condition": "warn",
        "no-control-regex": "error",
        "no-debugger": "off",
        "no-dupe-args": "error",
        "no-dupe-keys": "error",
        "no-duplicate-case": "error",
        "no-empty": "error",
        "no-empty-character-class": "error",
        "no-ex-assign": "error",
        "no-extra-boolean-cast": "error",
        "no-extra-parens": ["warn", "all", { conditionalAssign: false, }],
        "no-extra-semi": "error",
        "no-func-assign": "error",
        "no-inner-declarations": ["error", "both"],
        "no-invalid-regexp": "error",
        "no-irregular-whitespace": "error",
        "no-obj-calls": "error",
        "no-prototype-builtins": "warn",
        "no-regex-spaces": "error",
        "no-sparse-arrays": "warn",
        "no-template-curly-in-string": "error",
        "no-unexpected-multiline": "error",
        "no-unreachable": "error",
        "no-unsafe-finally": "error",
        "no-unsafe-negation": "error",
        "use-isnan": "error",
        "valid-jsdoc": "warn",
        "valid-typeof": ["error", { requireStringLiterals: true, }],

        // best practices:
        "accessor-pairs": "error",
        "array-callback-return": "error",
        "block-scoped-var": "error",
        "class-methods-use-this": ["warn", {
            exceptMethods: [],
        }],
        "complexity": ["error", { "max": 11 }],
        "consistent-return": ["error", { treatUndefinedAsUnspecified: true }],
        "curly": ["error", "multi-line"],
        "default-case": "warn",
        "dot-location": ["error", "property"],
        "dot-notation": ["error", { allowKeywords: true }],
        "eqeqeq": ["warn", "smart"],
        "guard-for-in": "warn",
        "no-alert": "warn",
        "no-caller": "error",
        "no-case-declarations": "error",
        "no-div-regex": "error",
        "no-else-return": "error",
        "no-empty-function": "warn",
        "no-empty-pattern": "error",
        "no-eq-null": "error",
        "no-eval": "error",
        "no-extend-native": "error",
        "no-extra-bind": "error",
        "no-extra-label": "error",
        "no-fallthrough": "error",
        "no-floating-decimal": "off",
        "no-global-assign": ["error", {
            exceptions: [],
        }],
        "no-implicit-coercion": ["off", {
            boolean: false,
            number: false,
            string: false,
            allow: [],
        }],
        "no-implicit-globals": "error",
        "no-implied-eval": "error",
        "no-invalid-this": "off",
        "no-iterator": "error",
        "no-labels": ["error", {
            allowLoop: false,
            allowSwitch: false,
        }],
        "no-lone-blocks": "error",
        "no-loop-func": "error",
        "no-magic-numbers": ["off", {
            ignore: [0, -1, 1],
            ignoreArrayIndexes: true,
            enforceConst: true,
            detectObjects: false,
        }],
        "no-multi-spaces": "error",
        "no-multi-str": "error",
        "no-new": "off",
        "no-new-func": "off",
        "no-new-wrappers": "error",
        "no-octal": "error",
        "no-octal-escape": "error",
        "no-param-reassign": ["warn", {
            props: true,
            ignorePropertyModificationsFor: [],
        }],
        "no-proto": "error",
        "no-redeclare": ["error", { builtinGlobals: true }],
        "no-restricted-properties": ["error"],
        "no-return-assign": ["error", "except-parens"],
        "no-return-await": "error",
        "no-script-url": "error",
        "no-self-assign": "error",
        "no-self-compare": "error",
        "no-sequences": "warn",
        "no-throw-literal": "error",
        "no-unmodified-loop-condition": "off",
        "no-unused-expressions": ["error", { allowShortCircuit: true, }],
        "no-unused-labels": "error",
        "no-useless-call": "error",
        "no-useless-concat": "warn",
        "no-useless-escape": "error",
        "no-useless-return": "error",
        "no-void": "off",
        "no-warning-comments": ["warn", {
            terms: ["todo", "fixme"],
            location: "start",
        }],
        "no-with": "error",
        "prefer-promise-reject-errors": ["off", { allowEmptyReject: true }],
        "radix": "error",
        "require-await": "off",
        "vars-on-top": "error",
        "wrap-iife": ["error", "outside", { functionPrototypeMethods: true }],
        "yoda": ["error", "always", {
            onlyEquality: true,
        }],

        // strict:
        "strict": ["error", "safe"],

        // variables:
        "init-declaration": "off",
        "no-catch-shadow": "error",
        "no-delete-var": "off",
        "no-label-var": "error",
        "no-restricted-globals": "off",
        "no-shadow": "error",
        "no-shadow-restricted-names": "error",
        "no-undef": "error",
        "no-undef-init": "error",
        "no-undefined": "off",
        "no-unused-vars": ["error", {
            vars: "all",
            args: "all", // "after-used",
            ignoreRestSiblings: true,
            caughtErrors: "none",
        }],
        "no-use-before-define": ["error", {
            functions: false,
            variables: true,
            classes: true,
        }],

        // node
        "callback-return": ["warn", ["callback", "cb"]],
        "global-require": "warn",
        "handle-callback-err": "off",
        "no-mixed-requires": "off",
        "no-new-require": "error",
        "no-path-concat": "error",
        "no-process-env": "off",
        "no-restricted-modules": "off",
        "no-sync": "off",

        // style:
        "array-bracket-spacing": ["error", "never"],
        "block-spacing": ["error", "always"],
        "brace-style": ["error", "1tbs", { allowSingleLine: true }],
        "camelcase": ["error", { properties: "always" }],
        "capitalized-comments": ["off", "never"],
        "comma-spacing": ["error", { before: false, after: true }],
        "comma-style": ["error", "last"],
        "computed-property-spacing": ["error", "never"],
        "consistent-this": ["off"],
        "eol-last": ["error", "always"],
        "func-call-spacing": ["error", "never"],
        "func-name-matching": ["off", "always", {
            includeCommonJSModuleExports: false,
        }],
        "func-names": ["off", "as-needed"],
        "func-style": ["off", "expression"],
        "id-blacklist": ["off"],
        "id-length": ["off", { min: 2 }],
        "id-match": ["off"],
        "indent": ["error", 4, {
            SwitchCase: 1,
            VariableDeclarator: 1,
            outerIIFEBody: 1,
            FunctionDeclaration: {
                parameters: 1,
                body: 1,
            },
            FunctionExpression: {
                parameters: 1,
                body: 1,
            },
        }],
        "jsx-quotes": "off",
        "key-spacing": ["error", { beforeColon: false, afterColon: true }],
        "keyword-spacing": ["error", {
            before: true,
            after: true,
            overrides: {}
        }],
        "line-comment-position": "off",
        "linebreak-style": ["error", "unix"],
        "lines-around-comment": "off",
        "lines-around-directive": ["error", { before: "never", after: "always" }],
        "max-depth": ["warn", { max: 4 }],
        "max-len": ["error", {
            code: 120,
            ignoreUrls: true,
            ignoreComments: false,
            ignoreRegExpLiterals: true,
            ignoreStrings: true,
            ignoreTemplateLiterals: true,
        }],
        "max-lines": "off",
        "max-nested-callbacks": "off",
        "max-params": "off",
        "max-statements": "off",
        "max-statements-per-line": "off",
        "multiline-ternary": "off",
        "new-cap": ["error", {
            newIsCap: true,
            newIsCapExceptions: [],
            capIsNew: true,
            capIsNewExceptions: [],
        }],
        "new-parens": "error",
        "newline-after-var": "off",
        "newline-before-return": "off",
        "newline-per-chained-call": ["error", { ignoreChainWithDepth: 4 }],
        "no-array-constructor": "error",
        "no-bitwise": "off",
        "no-continue": "off",
        "no-inline-comments": "off",
        "no-lonely-if": "error",
        "no-mixed-operators": ["off", {
            groups: [
                ["+", "-", "*", "/", "%", "**"],
                ["&", "|", "^", "~", "<<", ">>", ">>>"],
                ["==", "!=", "===", "!==", ">", ">=", "<", "<="],
                ["&&", "||"],
                ["in", "instanceof"]
            ],
            allowSamePrecedence: false
        }],
        "no-mixed-spaces-and-tabs": "error",
        "no-multi-assign": "off",
        "no-multiple-empty-lines": ["warn", { max: 2, maxEOF: 1 }],
        "no-negated-condition": "off",
        "no-nested-ternary": "off",
        "no-new-object": "error",
        "no-plusplus": "off",
        "no-restricted-syntax": ["error", "WithStatement"],
        "no-tabs": "error",
        "no-ternary": "off",
        "no-trailing-spaces": "error",
        "no-underscore-dangle": "error",
        "no-unneeded-ternary": "error",
        "no-whitespace-before-property": "error",
        "nonblock-statement-body-position": ["error", "beside"],
        "object-curly-newline": "off",
        "object-curly-spacing": ["error", "always"],
        "object-property-newline": ["error", { allowMultiplePropertiesPerLine: true }],
        "one-var": "off",
        "one-var-declaration-per-line": "off",
        "operator-assignment": ["warn", "always"],
        "operator-linebreak": ["error", "before"],
        "padded-blocks": ["error", "never"],
        "quote-props": ["warn", "as-needed", { keywords: false, unnecessary: true, numbers: false }],
        "quotes": ["error", "double"],
        "require-jsdoc": "off",
        "semi": ["error", "always"],
        "semi-spacing": ["error", { before: false, after: true }],
        "sort-keys": "off",
        "sort-vars": "off",
        "space-before-blocks": ["error", "always"],
        "space-before-function-paren": ["error", {
            anonymous: "never",
            named: "never",
            asyncArrow: "always",
        }],
        "space-in-parens": ["error", "never"],
        "space-infix-ops": "error",
        "space-unary-ops": ["error", {
            words: true,
            nonwords: false,
        }],
        "spaced-comment": ["error", "always"],
        "template-tag-spacing": ["error", "never"],
        "unicode-bom": ["error", "never"],
        "wrap-regex": "off",

        // es6
        "arrow-body-style": ["error", "as-needed"],
        "arrow-parens": ["error", "as-needed"],
        "arrow-spacing": ["error", { before: true, after: true }],
        "constructor-super": "error",
        "generator-star-spacing": ["error", { before: false, after: true }],
        "no-class-assign": "error",
        "no-confusing-arrow": ["warn", { allowParens: true }],
        "no-const-assign": "error",
        "no-dupe-class-members": "error",
        "no-duplicate-imports": "error",
        "no-new-symbol": "error",
        "no-restricted-imports": ["off"],
        "no-this-before-super": "error",
        "no-useless-computed-key": "error",
        "no-useless-constructor": "error",
        "no-useless-rename": "error",
        "no-var": "error",
        "object-shorthand": ["error", "always", {
            avoidQuotes: true,
        }],
        "prefer-arrow-callback": "error",
        "prefer-const": "error",
        "prefer-destructuring": ["off", {
            array: false,
            object: true,
        }],
        "prefer-numeric-literals": "error",
        "prefer-rest-params": "error",
        "prefer-spread": "error",
        "prefer-template": "off",
        "require-yield": "error",
        "sort-imports": "off",
        "symbol-description": "warn",
        "template-curly-spacing": ["error", "never"],
        "yield-star-spacing": ["error", "after"],
    }
};
