# zprofile

# EDITORS:

export EDITOR=vim
export VISUAL=vim
export PAGER=less

# Language

if [[ -z "$LANG" ]]; then
  export LANG="en_US.UTF-8"
fi

export LESS="-F -i -R"

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Path
path=(
    "$HOME/.bin"
    $path
)

# JAVA_HOME latest jdk available
export JAVA_HOME="$(echo /usr/lib/jvm/jdk*(/Nn[-1]))"

[ -f "${ZDOTDIR:-$HOME}/.zprofile.local" ] && source "${ZDOTDIR:-$HOME}/.zprofile.local" || true
