# zshenv
# .zshenv is sourced on ALL invocations of the shell, unless -f option is set

if [[ $SHLVL == 1 && ! -o LOGIN && -s ${ZDOTDIR:-$HOME}/.zprofile ]]; then
    source ${ZDOTDIR:-$HOME}/.zprofile
fi
