# zshenv
# .zshenv is sourced on ALL invocations of the shell, unless -f option is set

# EDITORS:

export EDITOR=vim
export VISUAL=vim
export PAGER=less

# Language

if [[ -z "$LANG" ]]; then
  export LANG="en_US.UTF-8"
fi

# Path
path=(
    "$HOME/.bin"
    "$HOME/.local/bin"
    $path
)

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# JAVA_HOME latest jdk available
export JAVA_HOME="$(echo /usr/lib/jvm/jdk*(/Nn[-1]))"

[ -f "${ZDOTDIR:-$HOME}/.zshenv.local" ] && source "${ZDOTDIR:-$HOME}/.zshenv.local" || true
