# zshrc
export ZSHRC=${${(%):-%x}:A}

ZRCDIR=${ZSHRC:h} # runcmd

ZSHDIR=${ZRCDIR:h}


fpath=(
    $fpath
#   $ZSHDIR/functions
#   $ZSHDIR/completions
)

path=(
    $path
)

autoload -U colors && colors
export LSCOLORS="Gxfxcxdxbxegedabagacad"

ZPLUG_HOME="${ZDOTDIR:-$HOME}/.zplug"

if [ ! -d $ZPLUG_HOME ]; then
    git clone https://github.com/zplug/zplug $ZPLUG_HOME
fi

source "$ZPLUG_HOME/init.zsh"

zplug "zplug/zplug"

# local
zplug "${ZSHDIR}/zshrc.d", from:local, use:"*.zsh", nice:15

# nvm
zplug "creationix/nvm", use:"nvm.sh", hook-build:"source nvm.sh && whence node > /dev/null || nvm install --lts"

# fzf
zplug "junegunn/fzf", \
    hook-build:"./install --no-update-rc --key-bindings --completion", \
    use: "$HOME/.fzf.zsh", \
    nice:16


# oh-my-zsh plugins
zplug "plugins/gitignore", from:oh-my-zsh
zplug "plugins/dircycle", from:oh-my-zsh
zplug "plugins/jump", from:oh-my-zsh
zplug "plugins/z", from:oh-my-zsh
zplug "plugins/composer", from:oh-my-zsh
zplug "plugins/gulp", from:oh-my-zsh, nice:10

zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-syntax-highlighting", nice:10
zplug "zsh-users/zsh-history-substring-search", nice:11

zplug "lukechilds/zsh-better-npm-completion", nice:10

zplug check || zplug install

zplug load

[ -f "${ZDOTDIR:-$HOME}/.zshrc.local" ] && source "${ZDOTDIR:-$HOME}/.zshrc.local"
