# zshrc

export ZSHRC=${${(%):-%x}:A}

ZSRCDIR=${ZSHRC:h}

path=(
    $path
)

autoload -U colors && colors
export LSCOLORS="Gxfxcxdxbxegedabagacad"

for file in $ZSRCDIR/zshrc.d/*.zsh; do
    source $file
done;

[ -f $HOME/.nvm/nvm.sh ] && source $HOME/.nvm/nvm.sh

ZPLUG_HOME=${ZDOTDIR:-$HOME}/.zplug

if [ ! -d $ZPLUG_HOME ]; then
    git clone https://github.com/zplug/zplug $ZPLUG_HOME
fi

source $ZPLUG_HOME/init.zsh

# oh-my-zsh plugins
zplug "plugins/command-not-found", from:oh-my-zsh
zplug "plugins/gitignore", from:oh-my-zsh
zplug "plugins/dirhistory", from:oh-my-zsh
zplug "plugins/jump", from:oh-my-zsh
zplug "plugins/z", from:oh-my-zsh
zplug "plugins/composer", from:oh-my-zsh
zplug "plugins/gulp", from:oh-my-zsh, nice:12

zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-syntax-highlighting", nice:10
zplug "zsh-users/zsh-history-substring-search", nice:11

zplug "lukechilds/zsh-better-npm-completion", nice:12

zplug check || zplug install

zplug load

bindkey "\eOA" history-substring-search-up
bindkey "\eOB" history-substring-search-down
